<?php
$url = home_url(('/'));

echo '<div class="wp-block-columns abinhas">';

	echo '<div class="wp-block-column">';
		echo '<div class="aba" style="margin-top: 20px;">';
			echo '<div class="aba-titulo">Qual é a vantagem de ter um plano?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Com um plano de manutenção adequado, sempre estarei de olho no seu website sem você precisar solicitar. Estarei atualizando, corrigindo e prevenindo diversos probleminhas que costumam se acumular à longo prazo quando não se tem o devido cuidado.</p>';
				echo '<p>Você não precisará mais ter receio de fazer atualizações, otimizações de banco de dados, nem com métodos de segurança &mdash; que são situações que <u>sempre</u> precisamos ficar de olho e realizar periodicamente no site.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">O pagamento é seguro?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim, é 100% seguro! O gateway de pagamento que o studio usa é o <a href="https://app.juno.com.br/#/onboarding/775831:b02a84" target="_blank" rel="nofollow noopener">Juno Pagamentos</a> para clientes residentes no Brasil e Stripe para as clientes que moram no exterior. Toda transação é realizada sob criptografia, com certificado de segurança ativado.</p>';
				echo '<p>A solicitação de pagamento aqui do site é enviada para o servidor do gateway através de um código criptografado. Depois, o gateway fará a solicitação ao seu cartão de crédito, e o mesmo permitirá (ou não) o andamento do seu pedido. Tudo isso em questão de segundos!</p>';
				echo '<p>Você não precisa ter conta em nenhum dos gateways usados no site para sua assinatura. O checkout é transparente, com zero burocracia. Basta ter apenas o número do seu cartão em mãos.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">O que é um sistema de assinatura?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Assinatura significa pagamento em recorrência, que é debitado automaticamente no seu <u>cartão de crédito</u> todo dia do mês referente ao dia da sua adesão. Por exemplo, se você fez a assinatura no dia 10, todo dia 10 será cobrado no seu cartão de crédito o valor referente ao plano que você escolheu.</p>';
				echo '<p>Não há cobrança de juros no cartão pois <strong>não é um pagamento parcelado</strong> e pode ser cancelado quando quiser.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Como saberei qual plano é ideal para mim?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Se você tem um site ou um blog simples, com poucas funcionalidades e com baixo tráfego, o plano ideal para você é o <em style="color:var(--cor-azul);">basic</em>.</p>';

				echo '<p>Caso tenha diversas funcionalidades e recursos, o <em style="color:var(--cor-verde);">standard</em> é perfeito pois há os benefícios ideais para manter todas as funcionalidades sempre bem redondinhas e funcionando a todo vapor.</p>';

				echo '<p>Agora, se você possui uma loja virtual, tem alto tráfego, não tem tempo algum para gerenciar seu site ou seu trabalho depende exclusivamente dele, o plano <em style="color:var(--cor-roxo);">premium</em> é ideal para ti! Ele é o mais completo dos planos, o único com monitoramento da segurança.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Moro fora do Brasil. Posso contratar um plano?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim! Todo serviço do studio é prestado de forma remota, então é atendido clientes de qualquer país do mundo! '.do_shortcode('[icone prefixo="fas" nome="heart" cor="rosa"]').' As assinaturas são cobradas em Real Brasileiro via Stripe, então <em>é preciso que o seu cartão seja internacional</em> para que a transação ocorra com sucesso!</p>';
				echo '<p style="line-height:1.3"><small>Obs: o studio não é responsável por taxas adicionais que podem ser cobradas na fatura de seu cartão, nem tarifas de conversão de moeda.</small></p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Assinei por engano ou me arrependi. Terei reembolso?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Você tem até 7 dias corridos após a adesão do plano para solicitar o cancelamento e obter o reembolso no seu cartão de crédito. Após esse período, não há formas reembolso, apenas o pedido de cancelamento da renovação.</p>';
				echo '<p>Logo no primeiro dia útil entrarei em contato contigo para solicitar seus dados de acesso, caso seja nova por aqui. Podemos retirar dúvidas e <a href="https://api.whatsapp.com/send?phone=5562996269941">conversar no whatsapp</a> sobre como podemos trabalhar juntas dentro da lista de benefícios do plano escolhido. '.do_shortcode('[icone prefixo="fas" nome="heart" cor="rosa"]').'</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Os valores incluem hospedagem ou registro de domínio?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Não. Hospedagem e registro de domínio são serviços ofertados por empresas provedoras de hospedagem, que cedem um espaço em seus servidores para armazenar sites e mantê-los "no ar".</p>'; 
				echo'<p>A manutenção do studio é um serviço profissional que visa manter e realizar procedimentos técnicos da gestão de um website (independente de onde está hospedado) para mantê-lo saudável, otimizado-o sempre que possível e mantê-lo em plena navegabilidade.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">É possível ter um plano híbrido?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim! Se nenhum dos planos acima lhe atende entre em contato comigo que faço um plano que atenda suas necessidades específicas. <strong>Entre em contato para conversamos!</strong> </p>';
				echo '<p>Mas lembre-se: um plano personalizado terá um custo diferente dos valores apresentados acima e irá depender da quantidade de benefícios requeridos no seu plano personalizado.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">É indicado ter plano mesmo estando dentro da garantia?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>No início da garantia, a manutenção realizada na implementação do layout é semelhante ao plano <em style="color:var(--cor-verde);">standard</em> nas ações preventivas. Durante 90 dias corridos o studio cobre qualquer problema de funcionamento e bugs provenientes do layout implementado &mdash; benefício que só tem nos planos.</p>';
				echo '<p>Desta forma, para manter os benefícios da garantia é interessante ter um plano mensal de acordo com o perfil do seu website para manter a sua saúde plena a longo prazo. 🥰</p>';
			echo '</div>';
		echo '</div>';
		
		echo '<div class="aba">';
			echo '<div class="aba-titulo">O monitoramento é 24/7? Tenho prioridade ao assinar?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>O monitoramento é realizado de 1x a 2x por semana em horário comercial, de preferência em horários de menor pico de visitas. Já o atendimento ao cliente sempre é durante as tardes de segunda à sexta, das 14h às 17h.</p>';
				echo '<p>Caso tenha uma fila de atendimento, as clientes assinantes têm prioridade neste atendimento, principamente quando há solicitação de solução de problemas.</p>';
			echo '</div>';
		echo '</div>';

		echo '<div class="aba">';
			echo '<div class="aba-titulo">Há prazo definido para serviços de design e de diagramação?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Os serviços de design e de diagramação de conteúdo <strong>são realizados exclusivamente sob solicitação.</strong> O prazo de produção será combinado entre nós, dependendo do tipo de material que precisa ser produzido ou diagramado.</p>';
				echo '<p><u>O studio não faz, sob hipótese alguma, produção conteúdo ou gestão de mídias sociais.</u> O serviço de diagramação é realizado apenas sob envio do conteúdo completo.</p>';
			echo '</div>';
		echo '</div>';


		
		

	echo '</div>';


	echo '<div class="wp-block-column">';
		echo '<div class="aba" style="margin-top: 20px;">';
			echo '<div class="aba-titulo">Como é sistema de newsletter ofertado no BONUS?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>O studio trabalha com o <a href="https://sendy.co/?ref=v0hCr" target="_blank">Sendy</a>, um software licenciado de email marketing auto-hospedado que permite enviar e-mails rastreáveis através do serviço <a href="https://aws.amazon.com/" target="_blank">Amazon Simple Email Service (SES)</a>, possibilitando enviar e-mails em massa com a autenticidade dos servidores Amazon.</p>';
				echo '<p>O Sendy possui uma boa integração com Wordpress, podendo ser integrado a formulários de contato e compras no Woocommerce. É o recurso perfeito para quem precisa de um meio simples e eficiente de armazenamento de emails.</p>';
				echo '<p>O software está hospedado nos servidores do studio e licenciado, com recurso API disponível para integrações com outros plugins Wordpress e aplicações externas, como o Zapier! 😎</p>';
				echo '<p>O Sendy que o studio '.do_shortcode('[afc]').' oferece <strong>não há limite de contatos, listas, autoresponders ou segmentações</strong>. A cota é inserida por disparos, ou seja, pelas <em>newsletter enviadas</em>. O limite de envios vai depender do plano, que vai de 2mil a 50mil disparos ao mês.</p>';
				echo '<p style="line-height:1.3"><small>Incluso no plano: apontamentos DNS de domínio, atribuição de email remetente e implementação de formulário no layout</small></p>';
			echo '</div>';
		echo '</div>';

		echo '<div class="aba">';
			echo '<div class="aba-titulo">Posso contratar apenas um plano de email marketing ao invés do pacote completo de manutenção?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p class="has-text-align-center">Sim! Veja abaixo as mensalidades.</p>';
				echo '<p class="has-text-align-center"><a class="button roxo pequeno" href="https://afcweb.design/servicos/email-marketing/">Ver planos de email mkt</a>';
				// echo '<p>Sim! Veja abaixo as mensalidades em relação à quantidade de disparos mensais:</p>';
				// echo '<table class="tabela-planos-trimestrais">';
				// 	echo '<tr>';
				// 		echo '<th>📬</th>';
				// 		echo '<th>2mil</th>';
				// 		echo '<th>10mil</th>';
				// 		echo '<th>50mil</th>';
				// 		echo '<th>100mil</th>';
				// 	echo '</tr>';
				// 	echo '<tr>';
				// 		echo '<td>Mensalidade</td>';
				// 		echo '<td>R$9,90</td>';
				// 		echo '<td>R$32,90</td>';
				// 		echo '<td>R$59,90</td>';
				// 		echo '<td>R$84,90</td>';
				// 	echo '</tr>';
				// 	echo '<tr>';
				// 		echo '<td>Templates *</td>';
				// 		echo '<td>-</td>';
				// 		echo '<td>1</td>';
				// 		echo '<td>2</td>';
				// 		echo '<td>3</td>';
				// 	echo '</tr>';
				// 	echo '<tr>';
				// 		echo '<td>&nbsp;</td>';
				// 		echo '<td><a href="'.$url.'?add-to-cart=5827" class="button mini azul">assinar</a></td>';
				// 		echo '<td><a href="'.$url.'?add-to-cart=5828" class="button mini verde">assinar</a></td>';
				// 		echo '<td><a href="'.$url.'?add-to-cart=5829" class="button mini">assinar</a></td>';
				// 		echo '<td><a href="'.$url.'?add-to-cart=5830" class="button mini rosa">assinar</a></td>';
				// 	echo '</tr>';
				// echo '</table>';
				// echo '<p style="line-height:1.3"><small>* São modelos prontos incluídos na contratação (não se renova ao mês, ok?) para você criar e-mail lindos com sua identidade.</small></p>';
			echo '</div>';
		echo '</div>';
		
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Qual é o tipo de hospedagem que se adequa aos planos?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Qualquer hospedagem que possua painel de gerenciamento de recursos do servidor que tenha acesso à contas FTP, ferramentas de otimização, gerenciamento de versão e edição de configurações PHP e de banco de dados mySQL com o gerenciador phpMyAdmin.</p>';
				echo '<p>Não sabe se sua hospedagem tem estes recursos? Entre em contato comigo para confirmar!</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Como os planos são cotados?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Os planos são baseados em estimativas de horas de serviço, que vai de 2h até 8h aproximadamente, dependendo do plano.</p>';
				echo '<p>Por ser constante, a hora do serviço tende a ficar mais acessível, com economia de até 50% se comparado a um serviço equivalente <em>(em horas trabalhadas)</em> fora do plano.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">É possível solicitar algo que não esteja dentro do plano?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim! Entretanto, pode haver cobrança de hora extra nas situações: <strong>1)</strong> caso exceda o limite de horas do seu plano escolhido; <strong>2)</strong> ou quando o serviço solicitado não faz parte da categoria dos benefícios incluídos do plano.</p>';
				echo '<p><strong>Atenção:</strong> qualquer serviço de design ou de programação que envolvam alterações significativas de layout, sejam para alterar o visual ou para inserir novas ferramentas, haverá cobrança por hora de serviço (independente do plano escolhido).</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Posso trocar de plano quando quiser?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim, basta cancelar sua assinatura atual presente dentro da sua Conta, na aba Planos, voltar a essa página e aderir ao plano desejado. Mas lembre-se: caso o cancelamento seja feito antes de encerrar o ciclo da sua última renovação, a mesma permanecerá vigente até encerrar seu prazo, ou seja, de 30 dias. Desta forma, <strong>o ideal é esperar que sua assinatura atual encerre o ciclo para contratar um novo plano.</strong></p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Posso cancelar a qualquer momento?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Sim! Não há período mínimo de adesão. Entretanto, vale lembrar que os benefícios da assinatura que contém elementos de <em>cota anual</em> serão perdidos caso o cancelamento seja feito em menos de 6 meses após a adesão.</p>';
				echo '<p>Para cancelar é só logar na sua conta do site do studio e acessar a aba Planos. Nela estará o seu plano vigente. Ao clica-lo é só clicar no botão "cancelar" e o mesmo não terá mais renovações automáticas.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Cancelei dias após à renovação do plano e quero reembolso. Posso ter meu dinheiro de volta da última recorrência do meu plano?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Não, você ainda terá os benefícios do seu plano até o ciclo se encerrar. O pedido de cancelamento após uma renovação só cancela a renovação automática.</p>';
				echo '<p>Você tem o direito de arrependimento do seu plano aderido apenas na primeira semana de adesão. Após este período, nenhum reembolso será realizado, apenas será realizado o cancelamento da renovação.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Posso contratar um plano e não possuir um layout do studio?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Não. Um plano de manutenção é um serviço adicional apenas para clientes que já possui um layout do studio.</p>';
				// echo '<p>Não. Um plano de manutenção é um serviço adicional apenas para clientes que já possui um layout do studio. O código dos layouts assinados pelo studio é 100% autoral, produzido sob uma metodologia que prevê edições na fase de pós-produção. Com isso, o processo de edição e de diagnóstico de solução de problemas é realizado com maior facilidade.</p>';
				// echo '<p>Cada designer / desenvolvedor tem sua forma de trabalhar. Portanto, o studio zela pela  os valores dos planos para clientes que possuem layout de terceiros são contabilizados de forma individual, mediante à uma análise para cotar possíveis complexidades inesperadas da produção terceirizada.</p>';
			echo '</div>';
		echo '</div>';
		echo '<div class="aba">';
			echo '<div class="aba-titulo">Afiliadas do studio tem assinatura mais barata?</div>';
			echo '<div class="aba-conteudo">';
				echo '<p>Por ter um custo por hora reduzido, os planos de manutenção não se adequam aos descontos de pós-produção para clientes afiliadas que possuem layout assinado pelo studio.</p>';
				echo '<p>Entretanto, a afiliada poderá indicar o studio e ganhar comissão por indicações das vendas dos produtos no site através de seu link de afiliada.</p>';
				echo '<p>Desta forma, você pode ter uma espécie de "cashback" de sua assinatura recomendando meus serviços para outras pessoas. '.do_shortcode('[icone prefixo="fas" nome="heart" cor="rosa"]').'</p>';
			echo '</div>';
		echo '</div>';

	echo '</div>';

echo '</div>';